### ISSUE TITLE
Off-by-one error in ZendService\Amazon\S3\Stream::stream_read

### ISSUE THREAD

**Issue by Whissi** [zendframework/ZendService_Amazon#64]
In https://github.com/zendframework/ZendService_Amazon/blob/master/library/ZendService/Amazon/S3/Stream.php#L175 is an off-by-one error:

Imagine you want to read a larger file (450215 bytes) using PHP's `readfile` function.
On first attempt, `stream_read` will be called with `$count` set to *8192* with the result that `$range_start` will be *0* (because it is the first call) and `$range_end` will be set to `0+8192=8192`. This will be used as *Range* header 0-8192 which will actually read *8193* bytes (see http://svn.tools.ietf.org/svn/wg/httpbis/specs/rfc7233.html#header.content-range) which you can see when you check length of `$response->getBody()` later.

The problem is now that we set `$this->_objectBuffer` to the larger value but extract only *8192* bytes via `$data = substr($this->_objectBuffer, $this->_position, $count);` and set *position* based on `strlen($data)`.

So while we use the correct position on our next `stream_read` call but `$this_>_objectBuffer` is larger than expected we will miss (truncate) data.

Quick fix: Change
```PHP
$range_end   = $this->_position+$count;
```
into
```PHP
$range_end   = $this->_position+$count-1;
```
Now we are really only requesting `$count` bytes and `$this->_objectBuffer` contains exactly what we have already processed so we don't miss (truncate) any data anymore.

**Comment by Xerkus** [comment]
Can you send a PR with tests fixing the issue?

**Comment by demiankatz** [comment]
@Xerkus, I took a stab at this in https://github.com/zendframework/ZendService_Amazon/pull/67 -- required heavy mocking, but it seems to demonstrate the issue effectively.

**Comment by Whissi** [comment]
Interesting mocking. I was thinking about providing a PR in the first place. I haven't done this yet because I am unsure about a good test case: The problem with `str_repeat('X', 5000)` content is that you won't catch invalid content. I think in the real example we got the same file size somehow but only noticed the problem because the actual content was invalid. I.e. we were requesting a XML document from S3 and when we tried to process that file we run into an error because the XML processor detected an invalid XML document.

**Comment by Xerkus** [comment]
I think in lines of generating repeating content, something like `pack('C*', ...range(0, 255));` (including null byte so it might also expose related problems if any).

Generated data can be written into memory stream to be used as a backend for mocks to do ranged reads.
Then a test case where S3\Stream can be used via `fread()` to make sure it works as a proper stream.

**Comment by demiankatz** [comment]
@Whissi and @Xerkus, thanks for the feedback. I have revised the test in #67 to be a bit more realistic, using packed data and confirming not just that the correct ranges are requested in the HTTP headers but also that the chunks sent back through substr calls reassemble into the expected original document. I've also added a second test to cover `fread()` behavior. The shared setup method that creates the test scenario is a bit complicated, and perhaps it would be more clear to write more redundant code that tells the story more clearly -- but this seems to get the job done. I think this is about the best we can do with mocking alone. I don't think using a memory stream would tell us anything more in this instance, since the chunk-reading is being handled by the HTTP protocol; without a live Amazon connection, we can't test whether that works, only whether we request the correct byte range. Hopefully this is good enough to merge now, but please let me know if you think further work is needed.

**Comment by Xerkus** [comment]
reason for a memory stream was to rely on its stream behavior, for some reason i thought there was a
function to read up to a position:
```php
->will($this->returnCallback(function ($a, $b, $c, $headers) {
    $range = explode('-', $headers['Range']); //range validity is checked in with()
    fseek($memoryStream, $range[0]);
    $partialData = fnonexistentPositionRead($memoryStream,  $range[1]);
    // ...
}));
```

**Comment by demiankatz** [comment]
@Xerkus, I see. That approach could certainly work too, and in some way makes the test code more readable. On the other hand, I think if that version of the test failed due to bad range header values, it might be less obvious from the failure message what was actually going wrong. Anyway, probably all just a matter of taste -- I'm still satisfied with my existing approach, but I'm willing to do further work if necessary.

**Comment by Xerkus** [comment]
@demiankatz ideally there should be granular tests that will check headers, tests that will check return values, tests that will check that stuff is working via fopen, tests that will check error conditions, eg failed request.

Such granular test will precisely pinpoint failure instead of requiring debugging of whole range of problems in a bigger test

**Comment by demiankatz** [comment]
@Xerkus, agreed. In general, the test suite for this component needs significant improvement -- but I think at this point we have done due diligence on ensuring that the issue described here is covered in multiple ways.
